### ISSUE TITLE
nautilus extension gnome 45

### ISSUE THREAD

**Issue by Thatoo** [gtkhash/gtkhash#173]
Hello,

I have install gtkhash but I can't see Hash in Nautilus File Properties like before.
I use Gnome 45 and it looks like this now : 
![image](https://github.com/gtkhash/gtkhash/assets/464782/c2f4c705-fab1-4c4d-bbfb-49abc826f591)

**Comment by tristanheaven** [comment]
It's broken since nautilus-42 #139
