### ISSUE TITLE
a patch for fix Debian  Bug#1074731: gtkhash: FTBFS

### ISSUE THREAD

**Issue by atzlinux** [gtkhash/gtkhash#175]
Hi,

  Debian bug report is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074731

msgfmt keyword should use  --keyword=WORD , not use a space,  --keyword WORD.

man msgfmt

       -kWORD, --keyword=WORD
              look for WORD as an additional keyword

[fix-msgfmt-keyword-use-space.patch.txt](https://github.com/user-attachments/files/16107800/fix-msgfmt-keyword-use-space.patch.txt)

**Comment by tristanheaven** [comment]
Applied your patch, thanks.
